# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: concourse-steampipe-resource
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - id: check
    binary: realcheck
    env: [CGO_ENABLED=0]
    goarch: [amd64]
    goos: [linux]
    ldflags:
      - -X github.com/cludden/concourse-go-sdk.Operation=check
  - id: in
    binary: in
    env: [CGO_ENABLED=0]
    goarch: [amd64]
    goos: [linux]
    ldflags:
      - -X github.com/cludden/concourse-go-sdk.Operation=in
  - id: out
    binary: out
    env: [CGO_ENABLED=0]
    goarch: [amd64]
    goos: [linux]
    ldflags:
      - -X github.com/cludden/concourse-go-sdk.Operation=out
archives:
  - files: [none*]
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - image_templates:
      - "ghcr.io/cludden/concourse-steampipe-resource:latest"
      - "ghcr.io/cludden/concourse-steampipe-resource:{{ .Tag }}"
      - "ghcr.io/cludden/concourse-steampipe-resource:{{ .FullCommit }}"
    extra_files:
      - bin/check
